#!/usr/bin/env python3
"""Load EvidenceIndex.csv generated by m04_Edge_Local_Forensic_dump.ps1 into EVIDENCE_INDEX.

PowerShell quick run (auto-detects paths when possible):
  python .\m04_Edge_Local_Forensic_INSERT_DB.py `
      --case-root "C:\SAFENET\DataSetGlobal\Forensic_Collect" `
      --db "C:\SAFENET\DB\forensic.db"
"""

import argparse
import csv
import sqlite3
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

SCRIPT_DIR = Path(__file__).resolve().parent


def guess_case_root() -> Optional[Path]:
    candidates = [
        Path.cwd() / "Forensic_Collect",
        SCRIPT_DIR.parent / "DataSetGlobal" / "Forensic_Collect",
        Path("C:/SAFENET/DataSetGlobal/Forensic_Collect"),
        Path("C:/Forensic_Collect"),
    ]
    for candidate in candidates:
        if candidate.is_dir():
            return candidate.resolve()
    return None


def guess_db_path() -> Optional[Path]:
    candidates = [
        Path.cwd() / "forensic.db",
        Path.cwd() / "DB" / "forensic.db",
        SCRIPT_DIR.parent / "DB" / "forensic.db",
        Path("C:/SAFENET/DB/forensic.db"),
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Importa EvidenceIndex.csv delle raccolte Edge user-centriche nel DB forense."
    )
    parser.add_argument(
        "--case-folder",
        action="append",
        help="Cartella singola che contiene EvidenceIndex.csv (opzione ripetibile).",
    )
    parser.add_argument(
        "--case-root",
        help="Cartella radice con più cartelle caso (usa tutte quelle con EvidenceIndex.csv).",
    )
    parser.add_argument(
        "--db",
        help="Percorso del DB SQLite forense (es. C:/SAFENET/DB/forensic.db).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Mostra cosa verrebbe inserito senza toccare il DB.",
    )
    return parser.parse_args()


def iter_case_folders(case_args: List[str], case_root: Optional[str]) -> Iterable[Path]:
    if case_args:
        for item in case_args:
            p = Path(item).resolve()
            if (p / "EvidenceIndex.csv").is_file():
                yield p
            else:
                print(f"[WARN] EvidenceIndex.csv non trovato in {p}")
    if case_root:
        root = Path(case_root).resolve()
        if not root.is_dir():
            print(f"[WARN] case-root non valido: {root}")
        else:
            for child in sorted(root.iterdir()):
                if not child.is_dir():
                    continue
                if (child / "EvidenceIndex.csv").is_file():
                    yield child


def read_evidence_csv(case_folder: Path) -> Tuple[str, Path, List[dict]]:
    csv_path = case_folder / "EvidenceIndex.csv"
    rows: List[dict] = []
    with csv_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append(row)
    run_label = case_folder.name
    return run_label, csv_path, rows


def normalise_user_ref(raw: str) -> str:
    trimmed = (raw or "").strip()
    return trimmed


def evidence_exists(cursor: sqlite3.Cursor, row: dict) -> bool:
    case_ref = (row.get("CaseRef") or "").strip()
    host_name = (row.get("Host") or "").strip()
    user_ref = normalise_user_ref(row.get("UserRef"))
    collected = (row.get("CollectedOn") or "").strip()
    source_type = (row.get("SourceType") or "").strip()
    relative_path = (row.get("RelativePath") or "").strip()

    if user_ref:
        cursor.execute(
            """
            SELECT evidence_id
            FROM EVIDENCE_INDEX
            WHERE case_ref = ?
              AND host_name = ?
              AND user_ref = ?
              AND collected_on_utc = ?
              AND source_type = ?
              AND relative_path = ?
            LIMIT 1
            """,
            (case_ref, host_name, user_ref, collected, source_type, relative_path),
        )
    else:
        cursor.execute(
            """
            SELECT evidence_id
            FROM EVIDENCE_INDEX
            WHERE case_ref = ?
              AND host_name = ?
              AND user_ref IS NULL
              AND collected_on_utc = ?
              AND source_type = ?
              AND relative_path = ?
            LIMIT 1
            """,
            (case_ref, host_name, collected, source_type, relative_path),
        )
    return cursor.fetchone() is not None


def insert_evidence(cursor: sqlite3.Cursor, row: dict) -> None:
    case_ref = (row.get("CaseRef") or "").strip()
    host_name = (row.get("Host") or "").strip()
    user_ref_raw = normalise_user_ref(row.get("UserRef"))
    user_ref = user_ref_raw if user_ref_raw else None
    collected = (row.get("CollectedOn") or "").strip()
    source_type = (row.get("SourceType") or "").strip()
    description = (row.get("Description") or "").strip()
    relative_path = (row.get("RelativePath") or "").strip()

    cursor.execute(
        """
        INSERT INTO EVIDENCE_INDEX (
            case_ref,
            host_name,
            user_ref,
            collected_on_utc,
            source_type,
            description,
            relative_path
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            case_ref,
            host_name,
            user_ref,
            collected,
            source_type,
            description,
            relative_path,
        ),
    )


def main() -> None:
    args = parse_args()

    if not args.case_folder and not args.case_root:
        guessed_root = guess_case_root()
        if guessed_root:
            args.case_root = str(guessed_root)
            print(f"[INFO] case-root non specificato, uso {args.case_root}")

    folders = list(iter_case_folders(args.case_folder or [], args.case_root))
    if not folders:
        raise SystemExit("Nessuna cartella caso valida trovata.")

    if not args.db:
        guessed_db = guess_db_path()
        if guessed_db:
            args.db = str(guessed_db)
            print(f"[INFO] db non specificato, uso {args.db}")
        else:
            raise SystemExit("Specificare --db (file forensic.db non trovato automaticamente).")

    db_path = Path(args.db).resolve()
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    total_inserted = 0
    for case_folder in folders:
        run_label, csv_path, rows = read_evidence_csv(case_folder)
        print(f"[INFO] Caso: {run_label} ({csv_path})")
        for row in rows:
            if evidence_exists(cur, row):
                continue
            if args.dry_run:
                print(
                    "[DRY] Inserirei -> case_ref=%s host=%s user=%s source=%s"
                    % (
                        (row.get("CaseRef") or "").strip(),
                        (row.get("Host") or "").strip(),
                        normalise_user_ref(row.get("UserRef")) or "(NULL)",
                        (row.get("SourceType") or "").strip(),
                    )
                )
                continue
            insert_evidence(cur, row)
            total_inserted += 1
        if not args.dry_run:
            conn.commit()

    conn.close()
    print(f"[SUMMARY] Righe inserite: {total_inserted}")
    if args.dry_run:
        print("[SUMMARY] DRY-RUN: nessuna modifica al DB.")


if __name__ == "__main__":
    main()
